- name: Build Jekyll for GitHub Pages
  uses: actions/jekyll-build-pages@v1.0.6
  with:
    # Directory where the source files reside.
    source: # optional, default is ./
    # Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.
    destination: # optional, default is ./_site
    # Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.
    future: # optional
    # The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.
    build_revision: # optional, default is ${{ github.sha }}
    # Verbose output
    verbose: # optional, default is true
    # GitHub token
    token: # default is ${{ github.token }}
    title: "Документация"
    description: A Jekyll theme for documentation
    baseurl: "/test_docs" # the subpath of your site, e.g. /blog
    url: "https://oalexeeva.github.io/test_docs/" # the base hostname & protocol for your site, e.g. http://example.com
    markdown: kramdown
    highlighter: rouge
    kramdown:
      input: GFM
      syntax_highlighter_opts:
      default_lang: sql
      css_class   : 'highlight'
      span:
        line_numbers: false
    block:
      line_numbers: false
      start_line: 1
    remote_theme: minima
    color_scheme: custom_colors
    #lang: ru
    search_enabled: true 
      search: 
      rel_url: false
